version: '3.1'
services:
  api:
    build: ./UsersCache
    ports:
      - 5000:80
      - 5001:443
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
  cache:
    image: bitnami/memcached
    ports:
      - 11211:11211
    environment:
      - MEMCACHED_CACHE_SIZE=128